### ISSUE TITLE
Criar todo backend do Like

### ISSUE THREAD

**Issue by Junior-Shyko** [Junior-Shyko/fcbnarede#5]
Criar todo backend do Like

### Critérios de aceitação
- [ ] Lista de usuários (nome e data do like) do like de um post ao clicar no ícone para visualizar
- [ ] Remover like do post
- [ ] Add um like ao post

### Modelo para base de espelho
![Captura de tela 2023-08-01 204549](https://github.com/Junior-Shyko/fcbnarede/assets/7341117/e51c5158-7c64-4568-9c3b-59b28182336c)
